---
- name: install the xorg packages
  pacman: name={{ item }} state=installed
  with_items:
    - xorg-server
    - xorg-xdm
    - xorg-xset
    - xdm-archlinux

- name: start the xdm service
  service: name=xdm-archlinux enabled=yes state=started

- name: install the rxvt-unicode package
  pacman: name=rxvt-unicode state=installed

- name: install the xterm package
  pacman: name=xterm state=installed

- name: install mesa-libgl
  pacman: name=mesa-libgl state=installed

- name: install the awesome window manager package
  pacman: name=awesome state=installed

- name: install fonts
  pacman: name={{ item }} state=installed
  with_items:
    - adobe-source-code-pro-fonts

- name: configure font directories
  with_items: "cd {{ item }} && mkfontscale && mkfontdir"
    - "/usr/share/fonts/adobe-source-code-pro"
